# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: udacitty
# "service" is the name of this project. This will also be added to your AWS resource names.
service: udagram

provider:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  tags: ${self:provider.stage}
  name: aws
  runtime: nodejs20.x
  environment:
    GROUPS_TABLE: groups-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GROUPS_TABLE}

functions:
  - GetGroups:
      handler: src/lambda/http/getGroups.handler
      events:
        - http:
            path: /groups
            method: get
            cors: true
  - PutGroups:
      handler: src/lambda/http/putGroup.handler
      events:
        - http:
            path: /groups
            method: post
            cors: true

resources:
  Resources:
    GroupsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GROUPS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
